// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectWordlist() {
  return window['go']['main']['App']['SelectWordlist']();
}

export function StartScan(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartScan'](arg1, arg2, arg3);
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}
