// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectWordlist():Promise<string>;

export function StartScan(arg1:string,arg2:number,arg3:string):Promise<void>;

export function StopScan():Promise<void>;
