// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectWordlist() {
  return window['go']['main']['App']['SelectWordlist']();
}

export function SendRepeater(arg1) {
  return window['go']['main']['App']['SendRepeater'](arg1);
}

export function StartIntruder(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartIntruder'](arg1, arg2, arg3, arg4, arg5);
}

export function StartScan(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartScan'](arg1, arg2, arg3);
}

export function StopIntruder() {
  return window['go']['main']['App']['StopIntruder']();
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}
